---
- name: Check and delete Disk Usage if over 60%
  hosts: ships
  become: true
  gather_facts: no
  tasks:

      
#task 1: to check the storage
    - name: Check The disk used precet.
      shell: |
        sudo df -m /orcaai/orcaai-storage | cut -d'%' -f1 | grep -oE '([0-9]{1,3}$)'
      register: Disk_status
    - debug:
        var: Disk_status.stdout_lines

#task 2: delete older files
    - name: delete older files 
      shell: |
       sudo find /orcaai/orcaai-storage/upload_saved -type f -mtime +60 -delete
       sudo find /orcaai/orcaai-storage/frames -type f -mtime +60 -delete
       sudo find /orcaai/orcaai-storage/data -type f -mtime +60 -delete
       sudo find /orcaai/orcaai-storage/tmp_scenes -type f -mtime +60 -delete

      when: Disk_status.stdout | int >= 60

#task 3: to check the storage
    - name: Check The disk used precet.
      shell: |
        sudo df -m /orcaai/orcaai-storage | cut -d'%' -f1 | grep -oE '([0-9]{1,3}$)'
      register: Disk_status1
    - debug:
        var: Disk_status1.stdout
